import type { Metadata } from "next";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="overflow-hidden">
        <div className="flex h-screen flex-col overflow-hidden">
          <div className="min-h-0 flex-1 overflow-hidden pb-20">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
