export type CoffeeBean = {
  id: number;
  image_url: string | null;
  brand: string | null;
  code: string | null;
  roast_level: string | null;
  name: string | null;
  country: string | null;
  name_ja: string | null;
  description_ja: string | null;
  flavor_notes: string[] | null;
  region: string | null;
  process: string | null;
  variety: string | null;
  elevation: string | null;
  farmer: string | null;
  farm: string | null;
  is_limited: boolean | null;
  status: string | null;
  created_at: string | null;
  updated_at: string | null;
};
